(() => {
  const groups = [
    ['Byliny', ['Jeżówka purpurowa','Rudbekia błyskotliwa','Aster nowoangielski','Dzielżan jesienny','Kocimiętka Faassena','Floks wiechowaty','Liatra kłosowa','Przetacznik kłosowy','Krwawnik pospolity','Gipsówka wiechowata'], ['fioletowy','zielone'], ['słońce','rabata bylinowa'], [.35,1.4,.35,1.0,'VII–IX']],
    ['Róże', ['Róża okrywowa','Róża rabatowa','Róża wielkokwiatowa','Róża pnąca','Róża parkowa','Róża angielska','Róża miniaturowa','Róża historyczna','Róża pomarszczona','Róża rugosa'], ['różowy','ciemnozielone'], ['słońce','rabata / pergola'], [.25,2.5,.25,1.8,'VI–X']],
    ['Cebulowe', ['Tulipan','Narcyz','Szafirek','Hiacynt','Czosnek ozdobny','Krokus','Lilia','Lilie azjatyckie','Zimowit jesienny','Śnieżyczka przebiśnieg'], ['wielobarwny','zielone'], ['słońce','rabatka / trawnik'], [.1,1.5,.1,.5,'III–VIII']],
    ['Trawy', ['Rozplenica japońska','Trzcinnik ostrokwiatowy','Kostrzewa sina','Sesleria jesienna','Proso rózgowate','Turzyca morrowa','Molinia arundinacea','Ostnica cieniutka','Imperata cylindryczna','Hakonechloa smukła'], ['beżowy','zielone / niebieskawe'], ['słońce / półcień','rabata naturalistyczna'], [.2,1.8,.2,1.2,'VI–X']],
    ['Krzewy', ['Pęcherznica kalinolistna','Tawuła japońska','Tawuła van Houtte’a','Forsycja pośrednia','Żylistek','Krzewuszka cudowna','Pięciornik krzewiasty','Kalina koralowa','Dereń biały','Jaśminowiec wonny'], ['biały','zielone'], ['słońce / półcień','żywopłot / rabata'], [.5,3,.5,2,'V–VII']],
    ['Hortensje', ['Hortensja ogrodowa','Hortensja drzewiasta','Hortensja dębolistna','Hortensja pnąca','Hortensja piłkowana','Hortensja kosmata','Hortensja Sargentiana','Hortensja bukietowa Limelight','Hortensja bukietowa Vanille Fraise','Hortensja bukietowa Polar Bear'], ['biały / różowy','zielone'], ['półcień','rabata wilgotna'], [.7,2.5,.7,2,'VI–X']],
    ['Iglaste', ['Jałowiec płożący','Jałowiec chiński','Żywotnik zachodni','Świerk biały Conica','Sosna górska','Sosna czarna','Jodła koreańska','Cyprysik groszkowy','Modrzew europejski','Cis pospolity'], ['—','zielone / niebieskawe'], ['słońce / półcień','skalniak / żywopłot'], [.3,12,.3,5,'—']],
    ['Drzewa', ['Brzoza pożyteczna','Klon palmowy','Klon pospolity','Grab pospolity','Buk pospolity','Dąb szypułkowy','Lipa drobnolistna','Jarząb pospolity','Świdośliwa Lamarcka','Wiśnia piłkowana'], ['biały / różowy','zielone'], ['słońce / półcień','soliter / aleja'], [1.5,25,1,12,'IV–VI']],
    ['Owoce', ['Jabłoń domowa','Grusza pospolita','Śliwa domowa','Wiśnia pospolita','Czereśnia','Morela','Brzoskwinia','Porzeczka czarna','Agrest','Malina właściwa'], ['biały / różowy','zielone'], ['słońce','sad / warzywnik'], [.5,8,.5,5,'IV–VII']],
    ['Pnącza', ['Powojnik wielkokwiatowy','Powojnik tangucki','Wiciokrzew pomorski','Wisteria chińska','Winobluszcz pięciolistkowy','Bluszcz pospolity','Milin amerykański','Rdestówka Auberta','Glicynia japońska','Aktinidia ostrolistna'], ['fioletowy / biały','zielone'], ['słońce / półcień','pergola / ściana'], [1,12,.3,5,'V–IX']],
    ['Warzywa', ['Pomidor','Papryka','Ogórek','Cukinia','Dynia','Jarmuż','Sałata','Marchew','Burak ćwikłowy','Czosnek pospolity'], ['żółty / biały','zielone'], ['słońce','warzywnik / donica'], [.15,3,.15,1,'V–X']],
    ['Zioła', ['Bazylia','Mięta pieprzowa','Tymianek pospolity','Oregano','Rozmaryn','Melisa lekarska','Estragon','Koper ogrodowy','Kolendra siewna','Lubczyk ogrodowy'], ['biały / różowy','zielone'], ['słońce / półcień','ziołownik / donica'], [.15,1.5,.15,1,'VI–IX']],
    ['Paprodzie', ['Pióropusznik strusi','Wietlica japońska','Paprotnik szczecinkozębny','Nerecznica samcza','Orliczka pospolita','Języcznik zwyczajny','Podrzeń żebrowiec','Onoklea wrażliwa','Woodsia elbejska','Cystopteris fragilis'], ['—','zielone'], ['cień / półcień','rabatka leśna'], [.3,1.2,.3,1,'—']],
    ['Okrywowe', ['Barwinek pospolity','Dąbrówka rozłogowa','Bodziszek korzeniasty','Pragnia syberyjska','Runianka japońska','Żurawka','Brunnera wielkolistna','Miodunka pstra','Gajowiec żółty','Kopytnik pospolity'], ['niebieski / biały','zielone / srebrzyste'], ['cień / półcień','pod drzewa'], [.1,.7,.2,.8,'IV–VIII']],
    ['Wodne', ['Lilia wodna','Grzybień biały','Tatarak zwyczajny','Pałka szerokolistna','Kosaciec żółty','Żabieniec babka wodna','Oczeret jeziorny','Manna mielec','Pontederia sercowata','Strzałka wodna'], ['biały / żółty','zielone'], ['słońce','staw / oczko wodne'], [.2,2,.3,1,'VI–IX']],
    ['Jednoroczne', ['Aksamitka rozpierzchła','Kosmos podwójnie pierzasty','Cynia wytworna','Nasturcja większa','Lwia paszcza','Werbena patagońska','Smagliczka nadmorska','Nagietek lekarski','Maciejka','Niecierpek'], ['żółty / różowy','zielone'], ['słońce / półcień','rabatka / donica'], [.1,1.5,.1,.6,'VI–X']],
    ['Sukulenty', ['Rojnik murowy','Rozchodnik okazały','Rozchodnik kamczacki','Rojniki pajęczynowate','Delosperma','Opuncja mrozoodporna','Skalnica','Gęsiówka kaukaska','Ubiorek wiecznie zielony','Czyściec wełnisty'], ['różowy / biały','srebrzyste'], ['słońce','skalniak / mur'], [.05,.7,.1,.6,'V–IX']],
    ['Lawendowe', ['Kocimiętka syberyjska','Perowskia łobodolistna','Bylica boże drzewko','Ruta zwyczajna','Santolina cyprysikowata','Lebiodka pospolita','Szałwia lekarska','Hyssop lekarski','Helichrysum italicum','Nagietek górski'], ['fioletowy / żółty','srebrzyste'], ['słońce','sucha rabata'], [.2,1.2,.2,.8,'VI–IX']],
    ['Cieniolubne', ['Funkia','Tojeść kropkowana','Tiarella sercolistna','Epimedium','Kokorycz','Zawilec japoński','Parzydło leśne','Rodgersja kasztanowcolistna','Trójsklepka owłosiona','Konwalijka dwulistna'], ['biały / różowy','zielone'], ['cień / półcień','ogród leśny'], [.2,1.8,.3,1.2,'IV–IX']],
    ['Popularne dodatkowe', ['Dalia','Mieczyk','Piwonia chińska','Irys bródkowy','Liliowiec','Łubin trwały','Malwa różowa','Naparstnica purpurowa','Mak wschodni','Dziewanna ogrodowa'], ['wielobarwny','zielone'], ['słońce / półcień','rabatka'], [.3,2,.3,1,'V–IX']]
  ];
  const common = groups.flatMap(([type,names,colors,place,[min,max,wmin,wmax,bloom]]) => names.map((name,i)=>({id:`g-${type}-${i}`,name,latin:'gatunek / odmiana ogrodowa',emoji:'✿',color:'#a9c6a3',size:wmax,height:`${min}–${max} m`,heightM:(min+max)/2,width:`${wmin}–${wmax} m`,flower:colors[0],foliage:colors[1],light:place[0],place:place[1],bloom,desc:`Popularna roślina do zastosowania w grupach ogrodowych. Sprawdź docelową wysokość i szerokość przed sadzeniem.`,category:type,rare:false})));
  const rareNames=['Kielichowiec wonny','Ambrowiec amerykański','Grujecznik japoński','Stewartia kameliowata','Parocja perska','Dereń kousa','Magnolia Siebolda','Magnolia parasolowata','Katalpa żółtokwiatowa','Metasekwoja chińska','Sasanka zwyczajna','Pełnik europejski','Mekonops bukwicolistny','Arisema amurska','Ciemiernik cuchnący','Cieszynianka wiosenna','Tojad mocny','Złocień arktyczny','Miodokwiat krzyżowy','Trytoma groniasta','Lagerstroemia indyjska','Lespedeza Thunberga','Dzwonkowiec szerokolistny','Zawilec wielkokwiatowy','Cykoria podróżnik','Pysznogłówka kropkowana','Miskant olbrzymi','Trzęślica modra Variegata','Turzyca palmowa','Hakonechloa macra Aureola','Róża moyesii','Róża glauca','Kalina japońska','Kalina bodnantska','Ośnieża karolińska','Kielichowiec chiński','Mahonia bealei','Skimmia japońska','Golteria pełzająca','Daphne mezereum','Cyprysik nutkajski','Sosna wejmutka','Świerk serbski Nana','Jodła hiszpańska','Buk pospolity Purple Fountain','Klon Shirasawy Aureum','Brzoza papierowa','Oczar pośredni','Paulownia puszysta','Akebia pięciolistkowa'];
  const rare=rareNames.map((name,i)=>({id:`rare-${i}`,name,latin:'rzadziej spotykana odmiana ogrodowa',emoji:'✦',color:['#d9b2c2','#a8c5dc','#d8c77d','#b8a7d8'][i%4],size:[.6,1,1.8,2.5][i%4],height:`${[.4,.8,1.5,2.5][i%4]}–${[1.2,2,4,8][i%4]} m`,heightM:[.8,1.4,2.7,5][i%4],width:`${[.4,.7,1.2,2][i%4]}–${[1,2,4,6][i%4]} m`,flower:['biały','różowy','żółty','fioletowy'][i%4],foliage:['zielone','purpurowe','srebrzyste','niebieskawe'][i%4],light:i%3===0?'cień / półcień':'słońce / półcień',place:['ogród kolekcjonerski','soliter','ogród leśny','rabata specjalistyczna'][i%4],bloom:'V–IX',desc:'Mniej oczywisty wybór do ogrodu. Warto sprawdzić mrozoodporność i dostępność lokalnie.',category:'Rzadziej spotykane',rare:true}));
  const featured=[{id:'lavender',name:'Lawenda',category:'Lawendowe',height:'40–60 cm',heightM:.6,width:'40–70 cm',flower:'fioletowy',foliage:'srebrzyste',light:'słońce',place:'sucha rabata',bloom:'VI–VIII',soil:'wapienna, sucha',color:'#b8a7d8',emoji:'✿'},{id:'hydrangea',name:'Hortensja bukietowa',category:'Hortensje',height:'1,5–2,2 m',heightM:2.2,width:'1,5–2 m',flower:'biały / różowy',foliage:'zielone',light:'półcień',place:'rabata wilgotna',bloom:'VII–X',soil:'kwaśna, wilgotna',color:'#f1cfca',emoji:'❀'},{id:'miscanthus',name:'Miskant chiński',category:'Trawy',height:'1,2–1,8 m',heightM:1.8,width:'1–1,3 m',flower:'beżowy',foliage:'zielone',light:'słońce',place:'rabata naturalistyczna',bloom:'IX–X',soil:'przepuszczalna, umiarkowana',color:'#c6bd8b',emoji:'〰'},{id:'sage',name:'Szałwia omszona',category:'Byliny',height:'30–50 cm',heightM:.5,width:'30–45 cm',flower:'fioletowy',foliage:'zielone',light:'słońce',place:'rabata bylinowa',bloom:'V–IX',soil:'żyzna, przepuszczalna',color:'#7799c5',emoji:'✦'},{id:'fern',name:'Paproć',category:'Paprodzie',height:'60–100 cm',heightM:1,width:'60–90 cm',flower:'—',foliage:'zielone',light:'cień / półcień',place:'rabatka leśna',bloom:'—',soil:'próchniczna, wilgotna',color:'#83aa83',emoji:'♧'},{id:'boxwood',name:'Bukszpan',category:'Krzewy',height:'50–100 cm',heightM:1,width:'50–80 cm',flower:'—',foliage:'zielone',light:'półcień',place:'obwódka',bloom:'—',soil:'próchniczna, umiarkowana',color:'#6f946e',emoji:'●'}];
  const soilByCategory={Byliny:'żyzna, przepuszczalna',Róże:'żyzna, umiarkowanie wilgotna',Cebulowe:'przepuszczalna, umiarkowana',Trawy:'przepuszczalna, umiarkowana',Krzewy:'próchniczna, umiarkowana',Hortensje:'kwaśna, wilgotna',Iglaste:'lekko kwaśna, przepuszczalna',Drzewa:'próchniczna, umiarkowana',Owoce:'żyzna, umiarkowana',Pnącza:'żyzna, umiarkowana',Warzywa:'żyzna, wilgotna',Zioła:'przepuszczalna, sucha',Paprodzie:'próchniczna, wilgotna',Okrywowe:'próchniczna, umiarkowana',Wodne:'mulista, wilgotna',Jednoroczne:'żyzna, przepuszczalna',Sukulenty:'sucha, bardzo przepuszczalna',Lawendowe:'wapienna, sucha',Cieniolubne:'próchniczna, wilgotna'};
  window.gardenowoCatalog = [...featured, ...common, ...rare].map(p=>({...p,soil:p.soil||soilByCategory[p.category]||'próchniczna, umiarkowana',moisture:p.category==='Sukulenty'||p.category==='Lawendowe'?'sucha':'umiarkowana',ph:p.category==='Hortensje'?'kwaśne 5–6':'lekko kwaśne–obojętne 6–7,5',frost:p.rare?'-18°C':'-23°C'}));
})();
